### ISSUE TITLE
The obtained AndroidManifest.xml differs from original

### ISSUE THREAD

**Issue by mjblackhorse** [hsiafan/apk-parser#57]
I try to use the tool to obtain AndroidManifest.xml of an apk file. But attribute with boolean type are all set to "false" while the original value should be "true"...

**Comment by timgoodchild** [comment]
I can confirm that this is an issue.

To give an example, I was previously using v2.0.15 where getManifestXml would return

```xml
<?xml version="1.0" encoding="utf-8"?>
<manifest .... >
	<uses-sdk android:minSdkVersion="14" />
	<application android:theme="@android:style/Theme.NoTitleBar.Fullscreen" android:label="xxxx" android:icon="xxxx" android:name="xxxx" android:debuggable="true" android:hardwareAccelerated="true">
		<activity android:theme="@android:style/Theme.NoDisplay" android:label="xxxx" android:name="xxxx" android:exported="true" android:excludeFromRecents="true" android:launchMode="singleInstance" android:hardwareAccelerated="false">
			<intent-filter>
				<action android:name="android.intent.action.MAIN" />
				<category android:name="android.intent.category.LAUNCHER" />
			</intent-filter>
		</activity>
		<activity android:name="xxxx" android:excludeFromRecents="true" android:screenOrientation="sensorPortrait">
			<intent-filter>
				<action android:name="" />
				<category android:name="android.intent.category.DEFAULT" />
			</intent-filter>
		</activity>
	</application>
</manifest>
```

After upgrading to 2.5.2, getManifestXml now returns the following for the same APK file

```xml
<?xml version="1.0" encoding="utf-8"?>
<manifest ..... >
	<uses-sdk android:minSdkVersion="14" />
	<application android:theme="@android:style/Theme.NoTitleBar.Fullscreen" android:label="xxxx" android:icon="xxxx" android:name="xxxx" android:debuggable="false" android:hardwareAccelerated="false">
		<activity android:theme="@android:style/Theme.NoDisplay" android:label="xxxx" android:name="xxxx" android:exported="false" android:excludeFromRecents="false" android:launchMode="singleInstance" android:hardwareAccelerated="false">
			<intent-filter>
				<action android:name="android.intent.action.MAIN" />
				<category android:name="android.intent.category.LAUNCHER" />
			</intent-filter>
		</activity>
		<activity android:name="xxxx" android:excludeFromRecents="false" android:screenOrientation="sensorPortrait">
			<intent-filter>
				<action android:name="xxxx" />
				<category android:name="android.intent.category.DEFAULT" />
			</intent-filter>
		</activity>
	</application>
</manifest>
```

All boolean attributes that were returning true are now returning false, e.g.
```
android:debuggable="true" android:hardwareAccelerated="true"
```

**Comment by timgoodchild** [comment]
I've spent a bit of time debugging this and looking around the source.  When parsing a boolean attribute the code enters ParseUtils.readResValue, and falls into the section:

```java
case ResValue.ResType.INT_BOOLEAN:
                return ResourceValue.bool(buffer.getInt());
```
where buffer.getInt returns -1.  Why does it return -1?  I would expect this to return 0 or 1.
The code then creates a BooleanResourceValue which creates a boolean string from the expression value == 1.  Since value == -1 this evaluates to false and so this is the reason why the boolean attribute values of true are being lost.

Looking at the history, the code previously used the expression value != 1 (instead of value == 1).  This was changed in commit 786f391 by Taro Kobayashi on 27/09/2016.

One might be tempted to simply revert this change, however is it correct to do that?  That would be easier to answer if we knew why buffer.getInt() returns -1 instead of 0 or 1.  However there appears to be be very little documentation on the binary XML format.

**Comment by hsiafan** [comment]
Due to code comment of android framework, the value of boolean type can only be 0 or 1.

```c++
// The 'data' is either 0 or 1, for input "false" or "true" respectively.
TYPE_INT_BOOLEAN = 0x12,
```

However, now, the c++ code did treat non-zero value as true when parse boolean resource. And also, it may set -1 value to resource entry value when is string is "true".

see 
[ResourceTypes.h] (https://github.com/aosp-mirror/platform_frameworks_base/blob/master/libs/androidfw/include/androidfw/ResourceTypes.h#L303)
[ResourceTypes.cpp] (https://github.com/aosp-mirror/platform_frameworks_base/blob/master/libs/androidfw/ResourceTypes.cpp#L5573)
[ResourceTypes.cpp print_value](https://github.com/aosp-mirror/platform_frameworks_base/blob/master/libs/androidfw/ResourceTypes.cpp#L7045)

I will revert the commit https://github.com/hsiafan/apk-parser/commit/786f3919edf0bbc343e37a19bccc1125ae4c4af2.

**Comment by timgoodchild** [comment]
This is now working as expected.  It's interesting to see the relevant AOSP source.
Thanks for turning this around quickly.
